<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<PlatformTarget>x64</PlatformTarget>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
		<nexoSdkBinPath>C:\nexoSDK_61.0.2.9383\Bin\</nexoSdkBinPath>
		<DeterministicSourcePaths>true</DeterministicSourcePaths>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="obj\**" />
	  <Compile Remove="NexoModule.Test\**" />
	  <EmbeddedResource Remove="obj\**" />
	  <EmbeddedResource Remove="NexoModule.Test\**" />
	  <None Remove="obj\**" />
	  <None Remove="NexoModule.Test\**" />
	  <Page Remove="obj\**" />
	  <Page Remove="NexoModule.Test\**" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="InsERT.Moria.API">
			<HintPath>$(nexoSdkBinPath)InsERT.Moria.API.dll</HintPath>
		</Reference>
		<Reference Include="InsERT.Moria.DaneDomyslne">
			<HintPath>$(nexoSdkBinPath)InsERT.Moria.DaneDomyslne.dll</HintPath>
		</Reference>
		<Reference Include="InsERT.Moria.ModelDanych">
			<HintPath>$(nexoSdkBinPath)InsERT.Moria.ModelDanych.dll</HintPath>
		</Reference>
		<Reference Include="InsERT.Moria.Sfera">
			<HintPath>$(nexoSdkBinPath)InsERT.Moria.Sfera.dll</HintPath>
		</Reference>
		<Reference Include="InsERT.Mox.Core">
			<HintPath>$(nexoSdkBinPath)InsERT.Mox.Core.dll</HintPath>
		</Reference>
		<Reference Include="InsERT.Mox.EntityFramework.Core">
			<HintPath>$(nexoSdkBinPath)InsERT.Mox.EntityFramework.Core.dll</HintPath>
		</Reference>
		<Reference Include="InsERT.Mox.EntityFrameworkSupport">
			<HintPath>$(nexoSdkBinPath)InsERT.Mox.EntityFrameworkSupport.dll</HintPath>
		</Reference>
		<None Include="$(nexoSdkBinPath)Xml.pak">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="$(nexoSdkBinPath)ijwhost.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="$(nexoSdkBinPath)Microsoft.Data.SqlClient.SNI.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="$(nexoSdkBinPath)Mrt.pak">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Zapqio.Runner.Module.Core" Version="1.0.0" />
	</ItemGroup>
	<!--Zip after publish-->
	<Target Name="ZipAfterPublish" AfterTargets="Publish">
		<PropertyGroup>
			<ZipFileName>$(MSBuildProjectName).zip</ZipFileName>
			<ZipFilePath>$(PublishDir)..\$(ZipFileName)</ZipFilePath>
		</PropertyGroup>
		<Delete Files="$(ZipFilePath)" Condition="Exists('$(ZipFilePath)')" />
		<ZipDirectory SourceDirectory="$(PublishDir)" DestinationFile="$(ZipFilePath)" />
		<Message Importance="High" Text="Created: $(ZipFilePath)" />
	</Target>

</Project>
